### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by cqep** [11273/zjy-work-answer#3]
按照说明安装之后 程序无法运行

**Comment by 11273** [comment]
输出什么内容呢

**Comment by cqep** [comment]
> 输出什么内容呢
> 

直接闪退出来

**Comment by cqep** [comment]
大佬，什么时候把职教云这个刷课的搞好呢？

**Comment by cqep** [comment]
2023-12-26 23:47:31,979 - ZJYMain.init_zjy - INFO - 登录失败:  msg: 系统异常,请截图联系客服处理~
程序退出

显示一个这个

**Comment by 11273** [comment]
这就奇怪了，这个是官方登录的信息，在这里可以登录成功吗
https://zjy2.icve.com.cn/index

**Comment by cqep** [comment]
> 这就奇怪了，这个是官方登录的信息，在这里可以登录成功吗
> https://zjy2.icve.com.cn/index

在您发的这个网站，可以登录上去 但是用您的这个软件就不行了 它一点进去就直接显示登录错误，密码账号都没有输入

**Comment by 11273** [comment]
密码账号都没有输入吗，这个要提前在代码里填账号密码

**Comment by cqep** [comment]
> 密码账号都没有输入吗，这个要提前在代码里填账号密码

原来如此

**Comment by cqep** [comment]
Traceback (most recent call last):
  File "E:\zjy-work-answer-main\zjy-work-answer-main\StartWork.py", line 26, in <module>
    mook_video.start(session)
  File "E:\zjy-work-answer-main\zjy-work-answer-main\ZJYMain\look_video.py", line 171, in start
    study_record(session, n, i['classId'])
  File "E:\zjy-work-answer-main\zjy-work-answer-main\ZJYMain\look_video.py", line 113, in study_record
    video_time = get_video_time(session, file_url)['args']['duration']
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
出现错误

**Comment by 11273** [comment]
我这可以正常，是什么课件呢，看错误应该是视频获取不到总时长

**Comment by cqep** [comment]
> 我这可以正常，是什么课件呢，看错误应该是视频获取不到总时长

       嗯，对视频获取不到时长 但是前面的那几个章节视频就可以刷，偏偏到这个章节就卡住了
       而且有一个课程直接给我跳过了 他直接给我开始刷第二个课程了 如图所示![IMG_20231231_160510.jpg](https://github.com/11273/zjy-work-answer/assets/153111824/bb1982d1-5423-4a3a-9321-61d14e91d3f4)

**Comment by cqep** [comment]
> 我这可以正常，是什么课件呢，看错误应该是视频获取不到总时长

嗯，大佬，我发现问题了 是那个课件本身的问题 点进去之后显示浏览器不支持该课件  希望大佬修复   直接跳过这种就行

**Comment by 11273** [comment]
OK，晚点有空修改代码

**Comment by cqep** [comment]
> OK，晚点有空修改代码

麻烦大佬了

**Comment by 11273** [comment]
已添加
