### ISSUE TITLE
进入课程后程序结束

### ISSUE THREAD

**Issue by FuDie0915** [11273/zjy-work-answer#8]
![Uploading 屏幕截图 2024-11-25 174503.png…]()

**Comment by 11273** [comment]
图片无法查看奥

**Comment by TilapiaLog** [comment]
> 图片无法查看奥

大概就是没报错没提示，直接结束运行了，输入完账号密码获取课程后

**Comment by 11273** [comment]
账号的课程有结束了的吗

**Comment by TilapiaLog** [comment]
> 账号的课程有结束了的吗

没有结束的

**Comment by 11273** [comment]
有测试账号或者是什么课程吗

**Comment by LLLuobuqi** [comment]
课程有的PPT课件无法刷但是不多，还有的课程是直接不会刷就像是没课件可以刷一样直接结束程序

**Comment by TilapiaLog** [comment]
> 有测试账号或者是什么课程吗

给个联系方式或者邮箱，我私发账号给你

**Comment by 11273** [comment]
> > 有测试账号或者是什么课程吗
> 
> 给个联系方式或者邮箱，我私发账号给你


MoosheetlmF@hotmail.com

**Comment by TilapiaLog** [comment]
> MoosheetlmF@hotmail.com

发送了,QQ邮箱发的

**Comment by 11273** [comment]
> > [MoosheetlmF@hotmail.com](mailto:MoosheetlmF@hotmail.com)
> 
> 发送了,QQ邮箱发的

收到

**Comment by 11273** [comment]
适配完成请使用最新版本
